In [1]:
import numpy as np

In [2]:
array1=np.array([3,4,5,6,7])
print(array1)
type(array1)

[3 4 5 6 7]


numpy.ndarray

In [4]:
array=np.array([[3,4],[5,6]])
print(array)

[[3 4]
 [5 6]]


In [5]:
numpy1=np.array([3,4,5,6,'9'])
print(numpy1)

['3' '4' '5' '6' '9']


In [7]:
numpy1

array(['3', '4', '5', '6', '9'], dtype='<U11')

In [8]:
numpy1=np.array([3,4,5,6,'9'],dtype='int')
print(numpy1)

[3 4 5 6 9]


In [10]:
arr1=np.array([4,5,6,7,8])
print(arr1)
arr1.ndim

[4 5 6 7 8]


1

In [12]:
arra1=np.array([[3,4],[5,6]])
arra1.ndim
print(arra1)

[[3 4]
 [5 6]]


In [13]:
arra1=np.array([[[3,4],[5,6]]])
arra1.ndim
print(arra1)

[[[3 4]
  [5 6]]]


In [14]:
print(arra1.shape)

(1, 2, 2)


In [16]:
arra1=np.array([[3,4,6],[5,6,7]])
arra1.ndim
print(arra1.shape)

(2, 3)


In [18]:
arr2=np.array([[[2,3],[4,5],[5,6]]])
arr2.shape

(1, 3, 2)

In [22]:
arr2=np.array([[[2,3,4],[4,5,6],[5,6,7],[3,6,8],[7,8,9]]])
arr2.shape

(1, 5, 3)

In [23]:
array1=np.array([4,5,6,7])
print(array1)

[4 5 6 7]


In [24]:
array1[2]

6

In [25]:
arra1=np.array([[3,4],[5,6]])
print(arra1[1,1])

6


In [26]:
arra1=np.array([[3,4],[5,6]])
print(arra1[0,1])

4


In [27]:
arra1

array([[3, 4],
       [5, 6]])

In [28]:
arra1[::]

array([[3, 4],
       [5, 6]])

In [30]:
arra1[0,:]

array([3, 4])